### ISSUE TITLE
Can not stop the server

### ISSUE THREAD

**Issue by nnbveh** [alexander-daniel/scvsc#16]
Trying your extension on Windows, it works fine but there's no way to stop the server so it keeps running no matter what, have to use the task manager to quit it...

there's a command to start the server, but it doesn't get assigned to the 's' variable like in scide, so can't do it from the code, or at least i don't know how. there's also no command in palette to do so from the keyboard shortcut...

**Comment by nnbveh** [comment]
i've tried to start the server through the code with s = Server.local;  but it gives me 'Cannot read properties of undefined (reading '1')' message...

**Comment by nnbveh** [comment]
Ah, i think i've figured it out, partially at least! s.quit;  doesn't work, but quit(s); does!!  i guess only one style is implemented and another isn't, whatever that mean...

**Comment by nnbveh** [comment]
oh, figured out one more thing: i can enclose the (s.quit;) and then it works....

**Comment by nnbveh** [comment]
okey, i've figured everything out so i guess i'll just close this, sorry)

**Comment by alexander-daniel** [comment]
I'd love to hear what the solution was! Thanks for giving it a go on Windows, I don't have a PC to test on

**Comment by nnbveh** [comment]
Actually the whole 'issue' was of my stupidity and not the extension itself
haha, you know how you can evaluate a like in scide without selecting
anything? Well, apparently you can only do it in vscode only if there's any
() in the code, otherwise you have to select it. So yeah, s.quit; works as
intended. But it would be nice to have a pallette command maybe to stop all
the active servers like the scide has, sometimes there are ghost servers
left...also, if you stop sclang and start it again it does not communicate
with the active sever anymore, at least that happened to me...

Thanks for your work, scide actually doesn't render anything in theain
window for some reason so I'm using this solution instead!
